In [2]:
import torch
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1


## tensors

### creating tensors

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item() #extract the value from the tensor

7

In [6]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim #number of square brackets

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1][0]

tensor(9)

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9]],
                        [[2, 3, 6],
                        [4, 1, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9]],

        [[2, 3, 6],
         [4, 1, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([2, 2, 3])

In [17]:
TENSOR[1][1][2]

tensor(5)

### random tensors

In [18]:
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.6992, 0.7960, 0.4113, 0.1346],
         [0.1119, 0.3601, 0.8878, 0.9801],
         [0.4711, 0.4385, 0.5535, 0.2311]],

        [[0.7022, 0.0766, 0.1411, 0.9101],
         [0.5183, 0.9679, 0.7978, 0.5514],
         [0.1510, 0.1902, 0.5789, 0.2385]]])

In [19]:
random_tensor.ndim

3

In [20]:
random_tensor.shape

torch.Size([2, 3, 4])

In [21]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### tensor with zeros and ones

In [22]:
zeros_tensor = torch.zeros(size = random_tensor.shape)
zeros_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [23]:
# zeros_tensor = torch.zeros(size = random_tensor.shape)
zeros_tensor * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [24]:
ones_tensor = torch.ones(size = random_tensor.shape)
ones_tensor

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [25]:
ones_tensor.dtype, random_tensor.dtype

(torch.float32, torch.float32)

### range of tensors

In [26]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### tensor datatypes

In [28]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #default is torch.float32
                               device=None, #default is cpu
                               requires_grad=False #default is False
                               )
float_32_tensor1 = torch.tensor([1.0, 2.0, 3.0],
                               dtype=None, #default is torch.float32
                               device=None, #default is cpu
                               requires_grad=False #default is False
                               )
float_32_tensor, float_32_tensor1

(tensor([3., 6., 9.]), tensor([1., 2., 3.]))

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_32_tensor.device

device(type='cpu')

In [31]:
float_16_tensor = float_32_tensor.to(dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_16_tensor + float_32_tensor

tensor([ 6., 12., 18.])

In [33]:
int_32_tensor = torch.tensor([1, 2, 3], 
                             dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [34]:
int_64_tensor = torch.tensor([3, 4, 5], 
                             dtype=torch.long)
int_64_tensor

tensor([3, 4, 5])

In [35]:
int_64_tensor + float_16_tensor

tensor([ 6., 10., 14.], dtype=torch.float16)

### get information from tensor

In [36]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2601, 0.3544, 0.5623, 0.8908],
        [0.4466, 0.5690, 0.8856, 0.3547],
        [0.9726, 0.9928, 0.0265, 0.0625]])

In [37]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")
print(f"Shape of tensor: {some_tensor.shape}")
some_tensor.size()

Datatype of tensor: torch.float32
Device tensor is stored on: cpu
Shape of tensor: torch.Size([3, 4])


torch.Size([3, 4])

### manipulating tensors

* addition
* subtraction

In [38]:
tensor = torch.tensor([1, 2, 3],
                      device='cuda',
                      dtype=torch.float16)
tensor * 10

tensor([10., 20., 30.], device='cuda:0', dtype=torch.float16)

In [39]:
tensor + 10

tensor([11., 12., 13.], device='cuda:0', dtype=torch.float16)

In [40]:
torch.mul(tensor, 10)

tensor([10., 20., 30.], device='cuda:0', dtype=torch.float16)

In [41]:
print(f"Product: {tensor * tensor}") # element-wise multiplication

Product: tensor([1., 4., 9.], device='cuda:0', dtype=torch.float16)


In [42]:
torch.matmul(tensor, tensor) # matrix multiplication

tensor(14., device='cuda:0', dtype=torch.float16)

In [43]:
torch.dot(tensor, tensor) # dot product

tensor(14., device='cuda:0', dtype=torch.float16)

In [44]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 465 μs, sys: 568 μs, total: 1.03 ms
Wall time: 666 μs


tensor(14., device='cuda:0', dtype=torch.float16)

In [45]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 137 μs, sys: 167 μs, total: 304 μs
Wall time: 215 μs


tensor(14., device='cuda:0', dtype=torch.float16)

In [46]:
torch.matmul(torch.rand(10, 2), torch.rand(2, 3)).size()

torch.Size([10, 3])

### shape errors

In [47]:
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]])
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

In [ ]:
tensor_B.T.shape

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

## Find the min, max of tensor

In [ ]:
x = torch.arange(0, 100, 10)
x

NameError: name 'torch' is not defined