In [2]:
import torch
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1


## tensors

### creating tensors

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item() #extract the value from the tensor

7

In [6]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim #number of square brackets

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1][0]

tensor(9)

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9]],
                        [[2, 3, 6],
                        [4, 1, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9]],

        [[2, 3, 6],
         [4, 1, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([2, 2, 3])

In [17]:
TENSOR[1][1][2]

tensor(5)

### random tensors

In [18]:
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.1224, 0.2194, 0.8620, 0.6129],
         [0.9204, 0.9464, 0.4915, 0.5437],
         [0.7497, 0.5864, 0.6507, 0.7925]],

        [[0.4575, 0.6257, 0.9973, 0.0192],
         [0.5994, 0.7320, 0.9452, 0.3213],
         [0.2273, 0.8689, 0.7552, 0.9624]]])

In [19]:
random_tensor.ndim

3

In [20]:
random_tensor.shape

torch.Size([2, 3, 4])

In [21]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### tensor with zeros and ones

In [22]:
zeros_tensor = torch.zeros(size = random_tensor.shape)
zeros_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [23]:
# zeros_tensor = torch.zeros(size = random_tensor.shape)
zeros_tensor * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [24]:
ones_tensor = torch.ones(size = random_tensor.shape)
ones_tensor

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [25]:
ones_tensor.dtype, random_tensor.dtype

(torch.float32, torch.float32)

### range of tensors

In [26]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### tensor datatypes

In [28]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #default is torch.float32
                               device=None, #default is cpu
                               requires_grad=False #default is False
                               )
float_32_tensor1 = torch.tensor([1.0, 2.0, 3.0],
                               dtype=None, #default is torch.float32
                               device=None, #default is cpu
                               requires_grad=False #default is False
                               )
float_32_tensor, float_32_tensor1

(tensor([3., 6., 9.]), tensor([1., 2., 3.]))

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_32_tensor.device

device(type='cpu')

In [31]:
float_16_tensor = float_32_tensor.to(dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_16_tensor + float_32_tensor

tensor([ 6., 12., 18.])

In [33]:
int_32_tensor = torch.tensor([1, 2, 3], 
                             dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [34]:
int_64_tensor = torch.tensor([3, 4, 5], 
                             dtype=torch.long)
int_64_tensor

tensor([3, 4, 5])

In [35]:
int_64_tensor + float_16_tensor

tensor([ 6., 10., 14.], dtype=torch.float16)

### get information from tensor

In [36]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6889, 0.6521, 0.1639, 0.0822],
        [0.1330, 0.4126, 0.3089, 0.0053],
        [0.2576, 0.8516, 0.5234, 0.6661]])

In [37]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")
print(f"Shape of tensor: {some_tensor.shape}")
some_tensor.size()

Datatype of tensor: torch.float32
Device tensor is stored on: cpu
Shape of tensor: torch.Size([3, 4])


torch.Size([3, 4])

### manipulating tensors

* addition
* subtraction

In [38]:
tensor = torch.tensor([1, 2, 3],
                      device='cuda',
                      dtype=torch.float16)
tensor * 10

tensor([10., 20., 30.], device='cuda:0', dtype=torch.float16)

In [39]:
tensor + 10

tensor([11., 12., 13.], device='cuda:0', dtype=torch.float16)

In [40]:
torch.mul(tensor, 10)

tensor([10., 20., 30.], device='cuda:0', dtype=torch.float16)

In [41]:
print(f"Product: {tensor * tensor}") # element-wise multiplication

Product: tensor([1., 4., 9.], device='cuda:0', dtype=torch.float16)


In [42]:
torch.matmul(tensor, tensor) # matrix multiplication

tensor(14., device='cuda:0', dtype=torch.float16)

In [43]:
torch.dot(tensor, tensor) # dot product

tensor(14., device='cuda:0', dtype=torch.float16)

In [44]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.53 ms, sys: 0 ns, total: 1.53 ms
Wall time: 1.18 ms


tensor(14., device='cuda:0', dtype=torch.float16)

In [45]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 317 μs, sys: 0 ns, total: 317 μs
Wall time: 229 μs


tensor(14., device='cuda:0', dtype=torch.float16)

In [46]:
torch.matmul(torch.rand(10, 2), torch.rand(2, 3)).size()

torch.Size([10, 3])

### shape errors

In [47]:
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]])
# torch.matmul(tensor_A, tensor_B)

In [48]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [49]:
tensor_B.T.shape

torch.Size([2, 3])

In [50]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Find the min, max of tensor

In [51]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [52]:
torch.min(x)

tensor(0)

In [53]:
x.min()

tensor(0)

In [54]:
torch.max(x)

tensor(90)

In [55]:
torch.mean(x.float()), torch.mean(x.type(torch.float32)) # mean of the tensor requires the tensor to be float


(tensor(45.), tensor(45.))

In [56]:
torch.sum(x)

tensor(450)

In [57]:
torch.argmin(x), torch.argmax(x)

(tensor(0), tensor(9))

## Reshaping, stacking, squeezing
* Reshape - reshape an input tensor into a defined shape
* View - return a view of an input tensor of a certain shape
* Stacking - combine multiple tensors along a certain dimension
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a tensor
* Permute - return a view of the input with dimensions permuted

### reshape

In [58]:
x = torch.arange(1., 11.)
x, x.shape, x.dtype

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([10]),
 torch.float32)

In [59]:
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [60]:
x_reshaped = x.reshape(2, 5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

### view

In [61]:
x = torch.arange(1., 11.)
x, x.shape, x.dtype

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([10]),
 torch.float32)

In [62]:
z = x.view(2, 5)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [63]:
z[0, 1] = 19
z

tensor([[ 1., 19.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [64]:
x

tensor([ 1., 19.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### stack

In [65]:
x = torch.arange(1., 6.).reshape(1, 5)
print(f"x: {x}")
print(f"x shape: {x.shape}")
print("\n")
x_stacked = torch.stack([x, x, x, x], dim=2)
print(f"x_stacked: {x_stacked}")
print(f"x_stacked shape: {x_stacked.shape}")

x: tensor([[1., 2., 3., 4., 5.]])
x shape: torch.Size([1, 5])


x_stacked: tensor([[[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.]]])
x_stacked shape: torch.Size([1, 5, 4])


### squeeze and unsqueeze

In [66]:
x_squeezed = x_stacked.squeeze()
print(f"x_squeezed: {x_squeezed}")
print(f"x_squeezed shape: {x_squeezed.shape}")
print(f"x_squeezed dim: {x_squeezed.dim()}")

x_squeezed: tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.]])
x_squeezed shape: torch.Size([5, 4])
x_squeezed dim: 2


In [67]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"x_unsqueezed: {x_unsqueezed}")
print(f"x_unsqueezed shape: {x_unsqueezed.shape}")
print(f"x_unsqueezed dim: {x_unsqueezed.dim()}")

x_unsqueezed: tensor([[[1., 1., 1., 1.]],

        [[2., 2., 2., 2.]],

        [[3., 3., 3., 3.]],

        [[4., 4., 4., 4.]],

        [[5., 5., 5., 5.]]])
x_unsqueezed shape: torch.Size([5, 1, 4])
x_unsqueezed dim: 3


### permute

In [68]:
x_original = torch.rand(size=(2, 4, 3)) # image tensor
print(f"x_original: {x_original}")
print(f"x_original shape: {x_original.shape}")

x_permuted = x_original.permute(2, 0, 1)
print(f"\nx_permuted: {x_permuted}")
print(f"x_permuted shape: {x_permuted.shape}")

x_original: tensor([[[0.7747, 0.7643, 0.6088],
         [0.6745, 0.2843, 0.7488],
         [0.1652, 0.0520, 0.8216],
         [0.4903, 0.1455, 0.8864]],

        [[0.3343, 0.9150, 0.0460],
         [0.3049, 0.8787, 0.9926],
         [0.7905, 0.0858, 0.2570],
         [0.7930, 0.1609, 0.8058]]])
x_original shape: torch.Size([2, 4, 3])

x_permuted: tensor([[[0.7747, 0.6745, 0.1652, 0.4903],
         [0.3343, 0.3049, 0.7905, 0.7930]],

        [[0.7643, 0.2843, 0.0520, 0.1455],
         [0.9150, 0.8787, 0.0858, 0.1609]],

        [[0.6088, 0.7488, 0.8216, 0.8864],
         [0.0460, 0.9926, 0.2570, 0.8058]]])
x_permuted shape: torch.Size([3, 2, 4])


In [69]:
x_original[0, 3, 2] = 520
print(f"x_permuted[2, 0, 3]: {x_permuted[2, 0, 3]}")

x_permuted[2, 0, 3]: 520.0


## Indexing

In [70]:
x = torch.arange(1, 10).reshape(1, 3, 3)

In [71]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [72]:
x[0][0] # equivalent to x[0, 0, :]

tensor([1, 2, 3])

In [73]:
x[0, 0, :]

tensor([1, 2, 3])

In [74]:
x[0][0][0]

tensor(1)

In [75]:
x[:, 0, 1]

tensor([2])

In [76]:
x[0][0][1]

tensor(2)

In [77]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [78]:
x[0, 1, 1]

tensor(5)

In [79]:
x[:, 1, 1]

tensor([5])

In [80]:
# to return 9
x[0, 2, 2]

tensor(9)

In [81]:
x[:, :, 2].squeeze() # to return 3,6,9

tensor([3, 6, 9])

In [82]:
x[0, :, 2]

tensor([3, 6, 9])

## pytorch and numpy

In [83]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # convert numpy array to tensor with float64
print(f"array: {array}")
print(f"tensor: {tensor}")

array: [1. 2. 3. 4. 5. 6. 7.]
tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [84]:
array.dtype #default dtype is float64

dtype('float64')

In [85]:
tensor.dtype

torch.float64

In [86]:
tensor = tensor.to(dtype=torch.float32)
tensor.dtype

torch.float32

In [87]:
array += 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [88]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor += 1
tensor = tensor + 1
tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

## reproducibility

In [89]:
random_A = torch.rand(3, 4)
random_B = torch.rand(3, 4)
print(f"random_A: {random_A}")
print(f"random_B: {random_B}")
print(random_A == random_B)

random_A: tensor([[0.7446, 0.1184, 0.1820, 0.7782],
        [0.1227, 0.4520, 0.1435, 0.3996],
        [0.6548, 0.7970, 0.4687, 0.7723]])
random_B: tensor([[0.0718, 0.0036, 0.5316, 0.6379],
        [0.6970, 0.7597, 0.5864, 0.6211],
        [0.6141, 0.4909, 0.9463, 0.6276]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [90]:
RANDOM_SEED = 43
torch.manual_seed(RANDOM_SEED)
random_C = torch.rand(3, 4)
random_D = torch.rand(3, 4)
print(f"random_C: {random_C}")
print(f"random_D: {random_D}")
print(random_C == random_D)

random_C: tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])
random_D: tensor([[0.5191, 0.5335, 0.5375, 0.7058],
        [0.4275, 0.2761, 0.8396, 0.1563],
        [0.1072, 0.7261, 0.3241, 0.8892]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [91]:
RANDOM_SEED = 43
gen = torch.Generator().manual_seed(RANDOM_SEED)

random_E = torch.rand(3, 4, generator=gen)

gen = torch.Generator().manual_seed(RANDOM_SEED)  # Reset the generator
random_F = torch.rand(3, 4, generator=gen)
print(f"random_E: {random_E}")
print(f"random_F: {random_F}")
print(random_E == random_F)

random_E: tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])
random_F: tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## On GPUs

In [96]:
device = "cuda"
device

'cuda'

In [93]:
torch.cuda.device_count()

8

In [94]:
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [97]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [101]:
# move tensor to cpu
tensor_on_gpu.cpu().numpy()

array([1, 2, 3])