In [116]:
import torch
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1


## tensors

### creating tensors

In [117]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [118]:
scalar.ndim

0

In [119]:
scalar.item() #extract the value from the tensor

7

In [120]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [121]:
vector.ndim

1

In [122]:
vector.shape

torch.Size([2])

In [123]:
#matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [124]:
MATRIX.ndim #number of square brackets

2

In [125]:
MATRIX[0]

tensor([7, 8])

In [126]:
MATRIX[1][0]

tensor(9)

In [127]:
MATRIX.shape

torch.Size([2, 2])

In [128]:
# tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9]],
                        [[2, 3, 6],
                        [4, 1, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9]],

        [[2, 3, 6],
         [4, 1, 5]]])

In [129]:
TENSOR.ndim

3

In [130]:
TENSOR.shape

torch.Size([2, 2, 3])

In [131]:
TENSOR[1][1][2]

tensor(5)

### random tensors

In [132]:
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.1513, 0.3258, 0.9345, 0.1126],
         [0.0101, 0.3759, 0.8142, 0.0555],
         [0.2511, 0.5970, 0.0885, 0.4952]],

        [[0.9112, 0.3280, 0.8063, 0.6560],
         [0.4045, 0.0603, 0.6418, 0.8657],
         [0.1800, 0.2086, 0.4895, 0.9150]]])

In [133]:
random_tensor.ndim

3

In [134]:
random_tensor.shape

torch.Size([2, 3, 4])

In [135]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### tensor with zeros and ones

In [136]:
zeros_tensor = torch.zeros(size = random_tensor.shape)
zeros_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [137]:
# zeros_tensor = torch.zeros(size = random_tensor.shape)
zeros_tensor * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [138]:
ones_tensor = torch.ones(size = random_tensor.shape)
ones_tensor

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [139]:
ones_tensor.dtype, random_tensor.dtype

(torch.float32, torch.float32)

### range of tensors

In [140]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [141]:
# tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### tensor datatypes

In [142]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #default is torch.float32
                               device=None, #default is cpu
                               requires_grad=False #default is False
                               )
float_32_tensor1 = torch.tensor([1.0, 2.0, 3.0],
                               dtype=None, #default is torch.float32
                               device=None, #default is cpu
                               requires_grad=False #default is False
                               )
float_32_tensor, float_32_tensor1

(tensor([3., 6., 9.]), tensor([1., 2., 3.]))

In [143]:
float_32_tensor.dtype

torch.float32

In [144]:
float_32_tensor.device

device(type='cpu')

In [145]:
float_16_tensor = float_32_tensor.to(dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [146]:
float_16_tensor + float_32_tensor

tensor([ 6., 12., 18.])

In [147]:
int_32_tensor = torch.tensor([1, 2, 3], 
                             dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [148]:
int_64_tensor = torch.tensor([3, 4, 5], 
                             dtype=torch.long)
int_64_tensor

tensor([3, 4, 5])

In [149]:
int_64_tensor + float_16_tensor

tensor([ 6., 10., 14.], dtype=torch.float16)

### get information from tensor

In [150]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6335, 0.1814, 0.8571, 0.7600],
        [0.3149, 0.1041, 0.4061, 0.4299],
        [0.3587, 0.2089, 0.9545, 0.6983]])

In [151]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")
print(f"Shape of tensor: {some_tensor.shape}")
some_tensor.size()

Datatype of tensor: torch.float32
Device tensor is stored on: cpu
Shape of tensor: torch.Size([3, 4])


torch.Size([3, 4])

### manipulating tensors

* addition
* subtraction

In [152]:
tensor = torch.tensor([1, 2, 3],
                      device='cuda',
                      dtype=torch.float16)
tensor * 10

tensor([10., 20., 30.], device='cuda:0', dtype=torch.float16)

In [153]:
tensor + 10

tensor([11., 12., 13.], device='cuda:0', dtype=torch.float16)

In [154]:
torch.mul(tensor, 10)

tensor([10., 20., 30.], device='cuda:0', dtype=torch.float16)

In [155]:
print(f"Product: {tensor * tensor}") # element-wise multiplication

Product: tensor([1., 4., 9.], device='cuda:0', dtype=torch.float16)


In [156]:
torch.matmul(tensor, tensor) # matrix multiplication

tensor(14., device='cuda:0', dtype=torch.float16)

In [157]:
torch.dot(tensor, tensor) # dot product

tensor(14., device='cuda:0', dtype=torch.float16)

In [158]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.03 ms, sys: 0 ns, total: 1.03 ms
Wall time: 624 μs


tensor(14., device='cuda:0', dtype=torch.float16)

In [159]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 160 μs, sys: 0 ns, total: 160 μs
Wall time: 134 μs


tensor(14., device='cuda:0', dtype=torch.float16)

In [160]:
torch.matmul(torch.rand(10, 2), torch.rand(2, 3)).size()

torch.Size([10, 3])

### shape errors

In [161]:
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]])
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

In [ ]:
tensor_B.T.shape

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

## Find the min, max of tensor

In [ ]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
x.min()

tensor(0)

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
torch.mean(x.float()), torch.mean(x.type(torch.float32)) # mean of the tensor requires the tensor to be float


(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x)

tensor(450)

In [ ]:
torch.argmin(x), torch.argmax(x)

(tensor(0), tensor(9))

## Reshaping, stacking, squeezing
* Reshape - reshape an input tensor into a defined shape
* View - return a view of an input tensor of a certain shape
* Stacking - combine multiple tensors along a certain dimension
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a tensor
* Permute - return a view of the input with dimensions permuted

In [169]:
x = torch.arange(1., 10.)
x, x.shape, x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), torch.float32)

In [177]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [178]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [179]:
x = torch.arange(1., 11.)
x, x.shape, x.dtype

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([10]),
 torch.float32)

In [180]:
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [181]:
x_reshaped = x.reshape(2, 5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))