In [227]:
import torch
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1


## tensors

### creating tensors

In [228]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [229]:
scalar.ndim

0

In [230]:
scalar.item() #extract the value from the tensor

7

In [231]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [232]:
vector.ndim

1

In [233]:
vector.shape

torch.Size([2])

In [234]:
#matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [235]:
MATRIX.ndim #number of square brackets

2

In [236]:
MATRIX[0]

tensor([7, 8])

In [237]:
MATRIX[1][0]

tensor(9)

In [238]:
MATRIX.shape

torch.Size([2, 2])

In [239]:
# tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9]],
                        [[2, 3, 6],
                        [4, 1, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9]],

        [[2, 3, 6],
         [4, 1, 5]]])

In [240]:
TENSOR.ndim

3

In [241]:
TENSOR.shape

torch.Size([2, 2, 3])

In [242]:
TENSOR[1][1][2]

tensor(5)

### random tensors

In [243]:
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.3655, 0.2389, 0.2759, 0.5553],
         [0.4453, 0.7866, 0.1933, 0.3014],
         [0.3367, 0.1764, 0.4771, 0.7297]],

        [[0.9661, 0.0322, 0.4801, 0.5607],
         [0.8221, 0.1751, 0.2068, 0.9864],
         [0.4329, 0.3843, 0.9700, 0.5680]]])

In [244]:
random_tensor.ndim

3

In [245]:
random_tensor.shape

torch.Size([2, 3, 4])

In [246]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### tensor with zeros and ones

In [247]:
zeros_tensor = torch.zeros(size = random_tensor.shape)
zeros_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [248]:
# zeros_tensor = torch.zeros(size = random_tensor.shape)
zeros_tensor * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [249]:
ones_tensor = torch.ones(size = random_tensor.shape)
ones_tensor

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [250]:
ones_tensor.dtype, random_tensor.dtype

(torch.float32, torch.float32)

### range of tensors

In [251]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [252]:
# tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### tensor datatypes

In [253]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #default is torch.float32
                               device=None, #default is cpu
                               requires_grad=False #default is False
                               )
float_32_tensor1 = torch.tensor([1.0, 2.0, 3.0],
                               dtype=None, #default is torch.float32
                               device=None, #default is cpu
                               requires_grad=False #default is False
                               )
float_32_tensor, float_32_tensor1

(tensor([3., 6., 9.]), tensor([1., 2., 3.]))

In [254]:
float_32_tensor.dtype

torch.float32

In [255]:
float_32_tensor.device

device(type='cpu')

In [256]:
float_16_tensor = float_32_tensor.to(dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [257]:
float_16_tensor + float_32_tensor

tensor([ 6., 12., 18.])

In [258]:
int_32_tensor = torch.tensor([1, 2, 3], 
                             dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [259]:
int_64_tensor = torch.tensor([3, 4, 5], 
                             dtype=torch.long)
int_64_tensor

tensor([3, 4, 5])

In [260]:
int_64_tensor + float_16_tensor

tensor([ 6., 10., 14.], dtype=torch.float16)

### get information from tensor

In [261]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3905, 0.7783, 0.7071, 0.5144],
        [0.2564, 0.8375, 0.1635, 0.1123],
        [0.6138, 0.3026, 0.2411, 0.7625]])

In [262]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")
print(f"Shape of tensor: {some_tensor.shape}")
some_tensor.size()

Datatype of tensor: torch.float32
Device tensor is stored on: cpu
Shape of tensor: torch.Size([3, 4])


torch.Size([3, 4])

### manipulating tensors

* addition
* subtraction

In [263]:
tensor = torch.tensor([1, 2, 3],
                      device='cuda',
                      dtype=torch.float16)
tensor * 10

tensor([10., 20., 30.], device='cuda:0', dtype=torch.float16)

In [264]:
tensor + 10

tensor([11., 12., 13.], device='cuda:0', dtype=torch.float16)

In [265]:
torch.mul(tensor, 10)

tensor([10., 20., 30.], device='cuda:0', dtype=torch.float16)

In [266]:
print(f"Product: {tensor * tensor}") # element-wise multiplication

Product: tensor([1., 4., 9.], device='cuda:0', dtype=torch.float16)


In [267]:
torch.matmul(tensor, tensor) # matrix multiplication

tensor(14., device='cuda:0', dtype=torch.float16)

In [268]:
torch.dot(tensor, tensor) # dot product

tensor(14., device='cuda:0', dtype=torch.float16)

In [269]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 0 ns, sys: 1.76 ms, total: 1.76 ms
Wall time: 1.25 ms


tensor(14., device='cuda:0', dtype=torch.float16)

In [270]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 410 μs, sys: 236 μs, total: 646 μs
Wall time: 453 μs


tensor(14., device='cuda:0', dtype=torch.float16)

In [271]:
torch.matmul(torch.rand(10, 2), torch.rand(2, 3)).size()

torch.Size([10, 3])

### shape errors

In [272]:
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]])
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

In [ ]:
tensor_B.T.shape

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

## Find the min, max of tensor

In [ ]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
x.min()

tensor(0)

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
torch.mean(x.float()), torch.mean(x.type(torch.float32)) # mean of the tensor requires the tensor to be float


(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x)

tensor(450)

In [ ]:
torch.argmin(x), torch.argmax(x)

(tensor(0), tensor(9))

## Reshaping, stacking, squeezing
* Reshape - reshape an input tensor into a defined shape
* View - return a view of an input tensor of a certain shape
* Stacking - combine multiple tensors along a certain dimension
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a tensor
* Permute - return a view of the input with dimensions permuted

### reshape

In [ ]:
x = torch.arange(1., 11.)
x, x.shape, x.dtype

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([10]),
 torch.float32)

In [ ]:
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [ ]:
x_reshaped = x.reshape(2, 5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

### view

In [ ]:
x = torch.arange(1., 11.)
x, x.shape, x.dtype

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([10]),
 torch.float32)

In [ ]:
z = x.view(2, 5)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
z[0, 1] = 19
z

tensor([[ 1., 19.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [ ]:
x

tensor([ 1., 19.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### stack

In [ ]:
x = torch.arange(1., 6.).reshape(1, 5)
print(f"x: {x}")
print(f"x shape: {x.shape}")
print("\n")
x_stacked = torch.stack([x, x, x, x], dim=2)
print(f"x_stacked: {x_stacked}")
print(f"x_stacked shape: {x_stacked.shape}")

x: tensor([[1., 2., 3., 4., 5.]])
x shape: torch.Size([1, 5])


x_stacked: tensor([[[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.]]])
x_stacked shape: torch.Size([1, 5, 4])


### squeeze and unsqueeze

In [ ]:
x_squeezed = x_stacked.squeeze()
print(f"x_squeezed: {x_squeezed}")
print(f"x_squeezed shape: {x_squeezed.shape}")
print(f"x_squeezed dim: {x_squeezed.dim()}")

x_squeezed: tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.]])
x_squeezed shape: torch.Size([5, 4])
x_squeezed dim: 2


In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"x_unsqueezed: {x_unsqueezed}")
print(f"x_unsqueezed shape: {x_unsqueezed.shape}")
print(f"x_unsqueezed dim: {x_unsqueezed.dim()}")

x_unsqueezed: tensor([[[1., 1., 1., 1.]],

        [[2., 2., 2., 2.]],

        [[3., 3., 3., 3.]],

        [[4., 4., 4., 4.]],

        [[5., 5., 5., 5.]]])
x_unsqueezed shape: torch.Size([5, 1, 4])
x_unsqueezed dim: 3


### permute

In [ ]:
x_original = torch.rand(size=(2, 4, 3)) # image tensor
print(f"x_original: {x_original}")
print(f"x_original shape: {x_original.shape}")

x_permuted = x_original.permute(2, 0, 1)
print(f"\nx_permuted: {x_permuted}")
print(f"x_permuted shape: {x_permuted.shape}")

x_original: tensor([[[0.5321, 0.1688, 0.1074],
         [0.5907, 0.5845, 0.1398],
         [0.0614, 0.9088, 0.9724],
         [0.4991, 0.7427, 0.7510]],

        [[0.8612, 0.6237, 0.0451],
         [0.0067, 0.3510, 0.0020],
         [0.7358, 0.7002, 0.5058],
         [0.2099, 0.5027, 0.1489]]])
x_original shape: torch.Size([2, 4, 3])

x_permuted: tensor([[[0.5321, 0.5907, 0.0614, 0.4991],
         [0.8612, 0.0067, 0.7358, 0.2099]],

        [[0.1688, 0.5845, 0.9088, 0.7427],
         [0.6237, 0.3510, 0.7002, 0.5027]],

        [[0.1074, 0.1398, 0.9724, 0.7510],
         [0.0451, 0.0020, 0.5058, 0.1489]]])
x_permuted shape: torch.Size([3, 2, 4])


In [ ]:
x_original[0, 3, 2] = 520
print(f"x_permuted[2, 0, 3]: {x_permuted[2, 0, 3]}")

x_permuted[2, 0, 3]: 520.0


## Indexing

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0][0] # equivalent to x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[:, 0, 1]

tensor([2])

In [ ]:
x[0][0][1]

tensor(2)

In [ ]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [ ]:
x[0, 1, 1]

tensor(5)

In [ ]:
x[:, 1, 1]

tensor([5])

In [ ]:
# to return 9
x[0, 2, 2]

torch.Size([1])

In [ ]:
x[:, :, 2].squeeze() # to return 3,6,9

tensor([3, 6, 9])

In [ ]:
x[0, :, 2]

tensor([3, 6, 9])

## pytorch and numpy

In [302]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # convert numpy array to tensor with float64
print(f"array: {array}")
print(f"tensor: {tensor}")

array: [1. 2. 3. 4. 5. 6. 7.]
tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [303]:
array.dtype #default dtype is float64

dtype('float64')

In [304]:
tensor.dtype

torch.float64

In [305]:
tensor = tensor.to(dtype=torch.float32)
tensor.dtype

torch.float32

In [306]:
array += 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [359]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor += 1
tensor = tensor + 1
tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

## reproducibility

In [385]:
random_A = torch.rand(3, 4)
random_B = torch.rand(3, 4)
print(f"random_A: {random_A}")
print(f"random_B: {random_B}")
print(random_A == random_B)

random_A: tensor([[0.8668, 0.8777, 0.1320, 0.8786],
        [0.9219, 0.6523, 0.6159, 0.6086],
        [0.4704, 0.9307, 0.2227, 0.3481]])
random_B: tensor([[0.8473, 0.7138, 0.1849, 0.4758],
        [0.1461, 0.9780, 0.6919, 0.6909],
        [0.5270, 0.0536, 0.0968, 0.5112]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [390]:
RANDOM_SEED = 43
torch.manual_seed(RANDOM_SEED)
random_C = torch.rand(3, 4)
random_D = torch.rand(3, 4)
print(f"random_C: {random_C}")
print(f"random_D: {random_D}")
print(random_C == random_D)

random_C: tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])
random_D: tensor([[0.5191, 0.5335, 0.5375, 0.7058],
        [0.4275, 0.2761, 0.8396, 0.1563],
        [0.1072, 0.7261, 0.3241, 0.8892]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [420]:
RANDOM_SEED = 43
gen = torch.Generator().manual_seed(RANDOM_SEED)

random_E = torch.rand(3, 4, generator=gen)

gen = torch.Generator().manual_seed(RANDOM_SEED)  # Reset the generator
random_F = torch.rand(3, 4, generator=gen)
print(f"random_E: {random_E}")
print(f"random_F: {random_F}")
print(random_E == random_F)

random_E: tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])
random_F: tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## On GPUs